# Generated by Django 2.2.7 on 2019-11-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191117_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('M', 'Manager'), ('EO', 'Employee Organization'), ('E', 'Employee')], default='E', max_length=15),
        ),
    ]
