# Generated by Django 2.2.7 on 2019-11-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
